// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhoawhyqajgxelnmfnkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRob2F3aHlxYWpneGVsbm1mbmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDY2NDAsImV4cCI6MjA2Mjk4MjY0MH0.fHAaYUbheHAKwcKQpEVJ5JLTG_4MjcBkwYa5VAQoNz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);